### PR TITLE
Remove chairs from template

### LINKED ISSUE #259: Chairs (etc.) in charters become stale
Listing chairs in charters creates redundant info that must be manually maintained.  Can we remove that info from the charter (and instead refer to a DB-backed source of truth)?  

I'm thinking of something like the data shown in:
https://www.w3.org/Member/Groups

### PR DESCRIPTION
**Pull request by samuelweiler**
To resolve https://github.com/w3c/charter-drafts/issues/259

### CODE REVIEW

**Comment by wseltzer** [comment]
@samuelweiler Chairs are often something reviewers want to see in evaluating a charter during review, and they're not frequently changed, so I wonder if there's a different way to solve the issue of synchronization.

**Comment by samuelweiler** [comment]
Two options:

1. Include the chairs at time of charter review, then remove the chairs from the charter at time of approval, much like an empty IANA considerations section is removed by the RFC Editor, or
2. Include the chairs in the email announcement seeking charter review, and leave them out of charters entirely.

**Comment by wseltzer** [comment]
I think we're looking for an API-based way to include chair information in charters *and* keep it updated.

**Comment by koalie** [comment]
I'm with @wseltzer because:
> [...] [chairs] are not frequently changed

therefore I don't know if it's actually an issue.

**Comment by wseltzer** [comment]
Not only do these changes happen infrequently, we want a record of when they do change. I think that puts us back to "manually update the charter and leave a note in the changelog at the bottom."

**Comment by samuelweiler** [comment]
> > [...] [chairs] are not frequently changed
> 
> therefore I don't know if it's actually an issue.

It's about a 10% error rate.  I suspect the low frequency of the changes actually contributes to the problem.  When you don't do a task (e.g. update chairs) often, you often forget how to do it "right" and miss steps.  And when we don't have a definitive list of all the places the chair names appear, we're going to miss some.

In addition to a mismatch in the Distributed Tracing WG which I found in May, today I see two other mismatches in our WGs:

Accessibility Guidelines Working Group
https://www.w3.org/groups/wg/ag/participants
https://www.w3.org/2019/12/ag-charter (also, this charter still says it is "proposed", and the old charter does not say that it is obsolete.)

JSON-LD Working Group
https://www.w3.org/groups/wg/json-ld/participants
https://www.w3.org/2018/03/jsonld-wg-charter.html

While the chairs match, I see mismatched team contacts in three WGs:
Education and Outreach Working Group 
Internationalization Working Group
Web Applications Working Group

**Comment by samuelweiler** [comment]
> Not only do these changes happen infrequently, we want a record of when they do change. I think that puts us back to "manually update the charter and leave a note in the changelog at the bottom."

I have observed that note not being added, e.g. no note was added to the the Distributed Tracing charter when it was fixed within the last month.

**Comment by samuelweiler** [comment]
Additionally, there are chair mismatches in these two IGs:

Web Payment Security Interest Group
Media and Entertainment Interest Group

**Comment by samuelweiler** [comment]
> Not only do these changes happen infrequently, we want a record of when they do change. I think that puts us back to "manually update the charter and leave a note in the changelog at the bottom."

I hear you.  I'm willing to close this issue and PR, but I do think there is a not-yet-addressed problem.

**Comment by koalie** [comment]
Thanks for the QA @samweiler!

> https://www.w3.org/2019/12/ag-charter (also, this charter still says it is "proposed", 

https://github.com/w3c/wcag/pull/1151

**Comment by koalie** [comment]
> Accessibility Guidelines Working Group
> https://www.w3.org/groups/wg/ag/participants
> https://www.w3.org/2019/12/ag-charter 

https://github.com/w3c/wcag/pull/1152

**Comment by svgeesus** [comment]
> I hear you. I'm willing to close this issue and PR, but I do think there is a not-yet-addressed problem.

I think the problem is that some Team contacts are unaware that they are supposed to update the charter (and append to the history section).

The solution seems to be better Team training and/or documentation.

I agree with @koalie that AC frequently want to know who will be chairing a newly-proposed group.

**Pull request closed without merging**
