### PR TITLE
[WebAssembly] Alternative to linking to the CG proposal repo

### PR DESCRIPTION
**Pull request by dschuff**
This would be an alternative to #250, in case there's some reason we shouldn't link to an external source or want an explicit list.

### CODE REVIEW

**Comment by dschuff** [comment]
cc @ericprud @dtig @lukewagner

**Comment by lukewagner** [comment]
If we feel we need an explicit list, lgtm.

**Comment by ericprud** [comment]
I resolved conflicts on this but leave it up to Wendy and PLH to decide whether it's better to reference an [external features document](https://github.com/WebAssembly/proposals/blob/master/README.md) or include a snapshot in a "such as" list. The previous charter went through with a [such as list](https://www.w3.org/2017/08/wasm-charter#web-assembly). As of 18 Dec, the WG was happy to follow W3M's advice on this.

**Comment by ericprud** [comment]
I resolved conflicts on this but leave it up to Wendy and PLH to decide whether it's better to reference an [external features document](https://github.com/WebAssembly/proposals/blob/master/README.md) or include a snapshot in a "such as" list. The previous charter went through with a [such as list](https://www.w3.org/2017/08/wasm-charter#web-assembly). As of 18 Dec, the WG was happy to follow W3M's advice on this.

**Comment by wseltzer** [comment]
Whichever the group prefers works fine for me. The list is nice for people skimming to see what's expected.

**Comment by ericprud** [comment]
OK, I suspect landing this is the most expeditious path forward.

**Pull request merged**
