### PR TITLE
[template] Adds a change log section in charters

### PR DESCRIPTION
**Pull request by plehegar**
From @dontcallmedom suggestion.

fyi @samuelweiler

### CODE REVIEW

**Comment by samuelweiler** [comment]
Interesting idea.  I wonder what happens when a major revision (re-charter) occurs, and I ask that having seen two different things:

- The new charter is published at the same URL as the old one
- The new charter goes in a new URL

The first option might lead to confusion, since it won't be clear which version of the charter had the change apply.  I have been embedding minor updates like in the history section  (see last line of the[ PING charter history table](https://www.w3.org/2019/09/privacy-ig-charter.html#about)).  That's ugly, but it avoids the confusion.

**Comment by plehegar** [comment]
Here is how I approach this nowadays:
1- for draft chater, those goes to this repo or wherever the group wants to iterate on it
2- for proposed charter (ie during AC review), the link for the AC goes to a new dated space on www.w3.org
3- for an approved charter, we also create a new dated space link on www.w3.org (different from the $2 one)
4- for an updated charter (ie, W3M agreed on a change that doesn't require a new AC review), we update the charter linked at $3 **in place**, updating the change log section as well.

Consequently, the case "The new charter is published at the same URL as the old one" is a bug in my mind. Probably created from an intent to have a "latest version" link to a group charter, which is becoming less useful nowadays since we're extracting the link from our DB anyway.

So, the change log only gets updated in the case $4. A new charter would have an empty change log section (ut the history section does reflect the changes from the previous charter).

**Comment by samuelweiler** [comment]
> Consequently, the case "The new charter is published at the same URL as the old one" is a bug in my mind.

in 2017 I asked Coralie how to do this, and she described something similar to what you describe.  Then a member of the Comm team did the "bug" thing.  The previous charter was no longer visible on the w3.org website, at all.

So while I agree that it's a bug, so long as these processes are being done by hand, it's a bug we need to account for.  (If the comm team makes the error, a team contact who only does this once or twice a year is bound to mess it up sometimes.)

**Comment by plehegar** [comment]
I was looking at https://www.w3.org/Guide/process/charter.html and it doesn't really document well on how we update charters. So, unless someone wants to do it, I'll take the action to update the Guide to clarify how charters links and updates are done., in coordination with @xueyuanjia .

**Comment by xueyuanjia** [comment]
> So, the change log only gets updated in the case $4. A new charter would have an empty change log section (ut the history section does reflect the changes from the previous charter).

+1 
* Charter History section: only record recharter history
  * for new charter (initial charter): to list the initial charter
  * for new charter (recharter): to list *notable* changes from previous charter(s). E.g., if a group rechartered twice, then the latest charter records 3 histories since its initial charter.

* Change Log section (for initial charter & recharters): only record updates within the current charter, including charter extension, chair & team contact changes, others that don't require AC review.

Regarding change log section, I'm hoping it's allowed to update the charter whenever there's a change. We used to suggest to collect/reflect changes all together when charter extended, which means we (comm, team contacts) may need to look back earlier archives and sometimes just forgot...

So, people can easily catch in the latest charter what those major changes are (from the History section) since the group initially created, as well as the editorial updates to the current version (from the change log) timely to avoid confusions.

**Comment by svgeesus** [comment]
How does this differ from the [existing History section](https://github.com/w3c/charter-drafts/blob/gh-pages/charter-template.html#L389)?

**Comment by svgeesus** [comment]
> I was looking at https://www.w3.org/Guide/process/charter.html and it doesn't really document well on how we update charters

The text at https://www.w3.org/Guide/process/charter.html#extension seems clear to me, except that there are changes (like new chairs) which should trigger the same update, but are not an extension. So **Updating the Charter End Date in the Charter** should perhaps be **Updating the Charter End Date or Chairs in the Charter**, and change _When a charter is extended, the Team_ to _When the chairs change, or a charter is extended, the Team_

**Review by svgeesus — APPROVED** [review]

**Pull request merged**
