### PR TITLE
mandate security and privacy consideration section(s)

### PR DESCRIPTION
**Pull request by samuelweiler**
resolving https://github.com/w3c/charter-drafts/issues/131

### CODE REVIEW

**Review by svgeesus — COMMENTED** [review]
LGTM

**Comment by svgeesus** [comment]
@ianbjacobs I like that wording, which would also resolve #144

**Comment by svgeesus** [comment]
Also fixed by https://github.com/w3c/charter-drafts/pull/268 which is to resolve #144

**Comment by samuelweiler** [comment]
> It's not clear to me that the template needs to go into detail about how editors organize those considerations into N sections.

For sec and privacy, I specifically want special sections.  It's not clear to me that this needs to be in the charter - I'm fine stripping it out of the charter entirely.   It's too verbose as it is.

Further, we want spec authors to do the consideration themselves - the section should not populated with review comments; it should be from the authors.

**Comment by samuelweiler** [comment]
Instead resolved via #300, though that still uses "should"

**Pull request closed without merging**
