### PR TITLE
More clearly define scope

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
I'm still worried that the Steve's stuff doesn't fit into our scope.

**Comment by marcoscaceres** [comment]
@LJWatson, I talk to Steve on Friday night about his specs. He is going to get a second implementation of the guidelines into an accessibility product - which, together with the W3C Validator, should allow us to progress the spec to CR.

**Comment by LJWatson** [comment]
>I talk to Steve on Friday night about his specs. He is going to get a second implementation of the guidelines into an accessibility product - which, together
with the W3C Validator, should allow us to progress the spec to CR.>
Yes, this has been the plan for some time. We have an expression of interest from one a11y tool vendor. @swickr 
 has also indicated that, because the content of this spec was previously at Rec inside the HTML5.0 spec, he is ok with it moving along on this basis.

**Comment by LJWatson** [comment]
I'm not sure we really need to make the scope this detailed?

**Comment by marcoscaceres** [comment]
Want to make sure it covers what came up during the f2f, but also constrained enough that we don’t get flooded with too many new things in the future. Should probably check with PLH tho.

**Pull request merged**
