### PR TITLE
Prepare new Browser Testing and Tools charter

### PR DESCRIPTION
**Pull request by sideshowbarker**
This adds the WebDriver BiDi spec as a deliverable.

### CODE REVIEW

**Comment by sideshowbarker** [comment]
@AutomatedTester, please review

**Comment by sideshowbarker** [comment]
@foolip, @jgraham also please weigh in with any suggestions

**Comment by AutomatedTester** [comment]
Thanks for putting this together @sideshowbarker 

I am not sure what we would be able to deliver in just 2 months (Sorry if I have misread the diff), work has been progressing nicely but I don't think we have any implementations started.

Could we have this moved until the middle of the year?

**Comment by AutomatedTester** [comment]
Thanks for putting this together @sideshowbarker 

I am not sure what we would be able to deliver in just 2 months (Sorry if I have misread the diff), work has been progressing nicely but I don't think we have any implementations started.

Could we have this moved until the middle of the year?

**Comment by sideshowbarker** [comment]
> I am not sure what we would be able to deliver in just 2 months (Sorry if I have misread the diff),

The 2 months until the end of this March is just for the extension which @plehegar already secured for us. Sorry, I realize now the diff makes it seem like this charter is instead for only two months — @jgraham asked pretty much the same thing on IRC.

> Could we have this moved until the middle of the year?

My plan is for the charter period to be at least 2 years (through the end of Q1 2023) if not three (end of Q1 2024). I just haven’t written that in yet because I need to ask the W3C Strategy team and @plehegar for guidance on exactly what length to put.

**Comment by AutomatedTester** [comment]
> My plan is for the charter period to be at least 2 years (through the end of Q1 2023) if not three (end of Q1 2024). I just haven’t written that in yet because I need to ask the W3C Strategy team and @plehegar for guidance on exactly what length to put.

Sounds good to me! Thanks Mike!

**Review by plehegar — APPROVED** [review]

**Comment by foolip** [comment]
Post-merge LGTM to these changes. Thanks @sideshowbarker!

**Pull request merged**
